MIN_TEXT_LIMIT = 50
MAX_TEXT_LIMIT = 350

NOUN_GROUP = ['NN', 'NNS', 'NNP', 'NNPS']
PRONOUN_GROUP = ['PRP', 'PRP$', 'WP', 'WP$']
VERB_GROUP = ['VB', 'VBD', 'VBG', 'VBN', 'VBP', 'VBZ']
ADJECTIVE_GROUP = ['JJ', 'JJR', 'JJS']
ADVERB_GROUP = ['RB', 'RBR', 'RBS', 'WRB']
PREPOSITION_GROUP = ['IN']
CONJUNCTION_GROUP = ['CC', 'IN']
INTERJECTION_GROUP = ['UH']