MIN_TEXT_LIMIT = 50
MAX_TEXT_LIMIT = 350

NOUN_GROUP = ['NN', 'NNS', 'NNP', 'NNPS']
VERB_GROUP = ['VB', 'VBD', 'VBG', 'VBN', 'VBP', 'VBZ']
ADJECTIVE_GROUP = ['JJ', 'JJR', 'JJS']
ADVERB_GROUP = ['RB', 'RBR', 'RBS', 'WRB']